import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import MegaMenuComponent from '@/components/menus/Mega';
import FooterComponent from '@/components/layout/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Creator Playground',
  description: 'Generated by Benggri',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MegaMenuComponent/>
        <main className="flex min-h-screen flex-col items-center">
          {children}
        </main>
        <FooterComponent/>
      </body>
    </html>
  )
}
